### ISSUE TITLE
question about your awesome config 

### ISSUE THREAD

**Issue by gitlerat** [tarneaux/.f#1]
regarding you checkout bb1c710ae9cea4eb69e85522d81bcb3eaa1d44f7
Do you build this awesome config from scratch or is there some guide which you followed, I ask because I like most of the things, but want to understand a little more of the organisation of code and so on, because it is different from a basic awesome install fresh config. :+1:

**Comment by tarneaux** [comment]
Hi, it's juste made basically from the example awesomewm config which I split into multiple files. I just use the awesomewm documentation and no particular guide, the main trick is to know what you want to do.
Splitting the config is something I did after like a week of using awesomewm because having one gigantic file annoyed me.
Everyone has a different way of splitting the config, but here's mine:
- autostart and `dofiles()` in rc.lua (that's the only place they can be anyway)
- then every other part of the config in the same dir. Most important files are `keys.lua` (for keybindings) and bar/bar.lua + bar/widgets/* which are the widgets that are put in the bar.

Hope it makes things a bit clearer.

**Comment by gitlerat** [comment]
Thank you! So no external widgets/snippets are used? Yeah a lot clearer!!
